############################################################
#
# The dockerfile for building image for executing scripts to
# crawl comic website.
#
############################################################
FROM ubuntu:18.04
MAINTAINER FATESAIKOU

# Install utils

RUN apt-get update && \
    apt-get install -y apt-utils && \
    apt-get install -y tmux git vim python3 python3-pip && \
    apt-get install -y nodejs

RUN pip3 install ipython requests beautifulsoup4 PyExecJS

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

ENV LANG en_US.utf8

WORKDIR /project
