############################################################
#
# The dockerfile for building image of my basic python environment
#
############################################################
FROM ubuntu:18.04
MAINTAINER FATESAIKOU

# Install utils

RUN apt-get update && \
    apt-get install -y apt-utils && \
    apt-get install -y tmux git vim python3 python3-pip 

RUN pip3 install ipython requests
